# ---
# Name: authoring_configuration
# ---
# PageController:
#   extensions:
#     - Symbiote\FrontendEditing\FrontendAuthoringController
---
Name: authoring_frontend_objects
---
Symbiote\FrontendObjects\Page\ObjectCreatorPageController:
  extensions:
    - Symbiote\FrontendEditing\FrontendObjectsAuthoringExtension
